// --- 1. STATE, DATA MODEL & TRANSLATION ---
const i18n = {
    de: {
        today_morning: "Guten Morgen", today_day: "Hallo", today_evening: "Guten Abend",
        today_of: "von", today_booked: "gebucht", today_missing_pre: "Noch", today_missing_post: "Stunden offen. {n} Aufgaben sind fällig oder überfällig.",
        today_complete: "Der Tag ist vollständig gebucht. {n} Aufgaben sind noch offen.",
        today_book_time: "Zeit buchen", mark_done: "Abschließen", wf_any_status: "— Jeder Status —", preset_cl_add: "Punkt hinzufügen", preset_cl_item_ph: "Checklistenpunkt", preset_cl_time_title: "Zeit in Stunden (optional)", today_running: "Laufende Timer", today_urgent: "Fällig und überfällig",
        today_all_tasks: "Alle Aufgaben", today_none_urgent: "Nichts überfällig", today_none_urgent_sub: "Alle terminierten Aufgaben liegen in der Zukunft.",
        today_this_week: "Diese Woche", today_next_week: "Nächste Woche", today_later: "Später", milestones_empty: "Keine Stacks mit Meilensteinen gefunden.", checklists_empty: "Keine Aufgaben mit Checklistenpunkten gefunden.", act_task_created: "Aufgabe „{n}“ erstellt", act_task_edited: "Aufgabe „{n}“ bearbeitet", act_task_done: "Aufgabe „{n}“ abgeschlossen", act_task_reopened: "Aufgabe „{n}“ wiedereröffnet", act_task_paused: "Aufgabe „{n}“ pausiert", act_task_resumed: "Aufgabe „{n}“ fortgesetzt", act_stack_created: "Stack „{n}“ erstellt", act_cp: "Checkpunkt", act_ms: "Meilenstein", act_cp_done: "{k} „{n}“ abgehakt", act_cp_reopened: "{k} „{n}“ wieder geöffnet", act_cp_edited: "{k} „{n}“ bearbeitet", act_cp_added: "{k} zu „{n}“ hinzugefügt", act_cp_deleted: "{k} „{n}“ gelöscht", act_stack_paused: "Stack „{n}“ pausiert", act_stack_resumed: "Stack „{n}“ fortgesetzt", act_stack_done: "Stack „{n}“ abgeschlossen",  act_stack_edited: "Stack „{n}“ bearbeitet", act_time_booked: "{h} h auf „{n}“ gebucht", today_activity: "Letzte Aktivitäten", today_no_activity: "Noch keine Aktivitäten", rel_now: "gerade eben",  today_unbooked: "Nicht gebucht", today_all_booked: "Alles gebucht", today_week_quota: "Wochenpensum", today_trend: "Stunden je Bucket", today_no_bookings: "Keine Buchungen", today_week_total: "Woche gesamt", today_last7: "letzte 7 Tage", today_status_dist: "Statusverteilung", today_open_checklist_extra: "+ {n} offene Checklistenpunkte/Meilensteine", today_open_stacks_extra: "+ {n} offene Stacks", status_todo: "Offen", status_inprogress: "In Arbeit", status_review: "Prüfung", today_prio_dist: "Prioritäten offen", today_done_share: "Erledigt gesamt", today_done_week: "diese Woche erledigt", today_open: "offen", today_overdue: "überfällig",
        tt_title: "Zeitkonto & offene Tage", tt_prev: "Vorheriger Monat", tt_next: "Nächster Monat", tt_add_absence: "Abwesenheit erfassen", tt_add_time: "Zeit erfassen", tt_detail_title: "Gebucht an gewählten Tagen", tt_detail_empty: "An den gewählten Tagen wurde noch nichts gebucht.", tt_deleted_task: "Gelöschte Aufgabe",
        tt_soll_todate: "Soll (bis heute)", tt_month_total: "Monat gesamt", tt_booked_h: "Erfasst", tt_from_tasks: "aus Aufgaben-Buchungen", tt_absence_h: "Abwesenheit", tt_absence_sub: "Urlaub / Krank / Feiertag", tt_saldo: "Saldo", tt_saldo_sub: "Ist + Abwesenheit − Soll", tt_open_days: "Offene Tage", tt_open_days_sub: "unvollständig gebucht",
        tt_open_outside: "offene Tage ausserhalb dieses Monats", tt_oldest: "ältester", tt_jump_there: "Hinspringen",
        tt_leg_ok: "Vollständig", tt_leg_partial: "Teilweise", tt_leg_missing: "Nicht gebucht", tt_leg_abs: "Abwesenheit", tt_leg_free: "Arbeitsfrei", tt_select_hint: "Tag anklicken zum Auswählen · Shift+Klick für Zeitraum",
        tt_selected: "Tag(e) ausgewählt", tt_half_day: "Halbe Tage", tt_remove_abs: "Abwesenheit entfernen", tt_abs_removed: "Abwesenheit(en) entfernt.", tt_nothing_removed: "Keine Abwesenheit zum Entfernen gefunden.",
        tt_open_list: "Offene Tage – schnell buchen", tt_select_all_open: "Alle offenen auswählen", tt_all_complete: "Alle Arbeitstage in diesem Monat sind vollständig gebucht.", tt_missing: "Fehlend", tt_of: "von", tt_book_task: "Zeit buchen",
        tt_abs_in_month: "Abwesenheiten in diesem Monat", tt_booked: "gebucht", tt_days_booked: "Tag(e) gebucht", tt_skipped_free: "arbeitsfreie Tage übersprungen", tt_no_open: "Keine offenen Tage vorhanden.", tt_nonworkday: "arbeitsfrei",
        tt_need_dates: "Bitte Von- und Bis-Datum wählen.", tt_range_invalid: "Das Bis-Datum liegt vor dem Von-Datum.", tt_abs_modal_title: "Abwesenheit erfassen", tt_abs_type: "Art der Abwesenheit", tt_from: "Von", tt_to: "Bis", tt_abs_modal_hint: "Arbeitsfreie Tage (z.B. Wochenenden) werden automatisch übersprungen.",
        abs_vacation: "Urlaub", abs_sick: "Krank", abs_holiday: "Feiertag", abs_other: "Kompensation",
        set_timeacct: "Zeitkonto (Soll-Zeiten)", set_timeacct_desc: "Legt fest, wie viele Stunden pro Arbeitstag gebucht sein müssen. Auf dieser Basis erkennt die Zeiterfassung unvollständig gebuchte Tage.", set_target_h: "Soll-Stunden / Arbeitstag", set_track_from: "Prüfung ab",
        view_today: "Hub", view_kanban: "Kanban Board", view_list: "Liste", view_notes: "Notizen", view_planner: "Planung", view_schedule: "Kalender", view_stakeholder: "Stakeholder", view_buckets: "Buckets", view_timeline: "Gantt-Diagramm", view_stacks: "Projekt-Stacks", view_checklists: "Checklisten", view_time: "Zeiterfassung", sched_history: "Verlauf", view_dependencies: "Abhängigkeiten", dep_start: "Startpunkt", dep_no_stack: "Ohne Stack", dep_depends_on: "Hängt ab von", dep_unlink_hint: "Klicken, um Verbindungen zu lösen", dep_unlink_confirm: "Alle Vorgänger-Verbindungen dieses Elements lösen?", dep_unlinked: "Verbindungen gelöst", sort_manual: "Manuell", sort_name: "Name", sort_due: "Fällig", sort_priority: "Priorität", dep_connect_mode: "Verbinden", dep_connect_on: "Verbinden-Modus: erst Quelle, dann Ziel antippen", dep_tap_target: "Jetzt Ziel-Element antippen", dep_drag_hint2: "Ziehen oder „Verbinden“ antippen", dep_precond: "Vorbedingungen (Checkpunkte)", dep_link_invalid: "Diese Verknüpfung ist nicht möglich (nur Aufgabe→Aufgabe oder Checkpunkt→Stack).", dep_drag_hint: "Knoten ziehen, um zu verknüpfen", dep_only_tasks: "Verknüpfungen sind nur zwischen Aufgaben möglich.", dep_exists: "Diese Verknüpfung besteht bereits.", dep_cycle: "Das würde einen Kreis erzeugen und ist nicht erlaubt.", dep_linked: "\"{a}\" ist jetzt Vorgänger von \"{b}\".", dep_end: "Endpunkt (gesperrt)", dep_ready: "Bereit", dep_blocked: "Gesperrt", dep_no_tasks: "Keine Aufgaben", dep_empty_title: "Keine Abhängigkeiten", dep_empty_sub: "Lege in einer Aufgabe Vorgänger fest, dann erscheinen hier die Ketten.",
        search: "Suchen...", new: "Neu", new_task: "Neue Aufgabe", new_stack: "Neues Stack",
        filter_hide_comp: "Abgeschlossene ausblenden", filter_hide_paused: "Pausierte ausblenden", filter_by: "Filtern nach:", btn_users: "Benutzer", btn_stacks: "Stacks", btn_sh: "Stakeholder", btn_buckets: "Buckets", btn_status: "Status",
        export_share: "Gefilterte Ansicht teilen (JSON)", export_excel_view: "Excel (Ansicht)", export_excel_time: "Excel (Zeiten)", export_pdf: "PDF (Gefiltert)", export_word: "Word Dokument (.doc)", export_ics: "Kalender (.ics) exportieren", export_backup: "Backup herunterladen", import_backup: "Backup / Geteilte Datei importieren",
        modal_rate: "Bewertung abgeben", modal_rate_desc: "Du hast dieses Projekt/Aufgabe abgeschlossen. Wie lief es?", rate_comm: "Kommunikation & Transparenz", rate_time: "Einhaltung von Zeitplänen", rate_qual: "Qualität der Ergebnisse", rate_team: "Zusammenarbeit & Teamdynamik", rate_crea: "Kreativität & Innovation", rate_satis: "Kundenzufriedenheit", rate_skip: "Überspringen", save: "Speichern", cancel: "Abbrechen", delete: "Löschen", share: "Teilen",
        merge_title: "Aufgaben zu Stack verbinden", merge_desc: "Wähle ein bestehendes Projekt-Stack oder erstelle ein neues.", merge_existing: "Bestehendes Stack:", merge_or: "ODER", merge_new: "Neues Stack erstellen (Name):", merge_btn: "Verbinden",
        marker_title_edit: "Marker bearbeiten", marker_title_new: "Neuer Marker", marker_name: "Name des Markers", marker_date: "Datum",
        time_title: "Zeiteintrag bearbeiten", time_task: "Aufgabe", time_date: "Datum", time_hours: "Stunden", time_note: "Notiz",
        task_new: "Aufgabe erstellen", task_edit: "Aufgabe bearbeiten", tab_gen: "Allgemein", tab_plan: "Planung & Zeiten", tab_detail: "Checkliste & Dateien", tab_rating: "Bewertung",
        t_name: "Aufgabenname", t_stack: "Zugehöriges Projekt-Stack", t_assignee: "Verantwortlich (Benutzer)", t_status: "Status", t_prio: "Priorität", prio_low: "Niedrig", prio_med: "Mittel", prio_high: "Hoch", t_sh: "Stakeholder", t_bucket: "Bucket (Kategorie)", t_start: "Startdatum", t_due: "Fälligkeitsdatum", t_est: "Geschätzter Aufwand (Std)", t_spent: "Bisheriger Aufwand (Std)", t_rec: "Wiederholung", t_rtf: "Notizen (Rich Text)", t_cl: "Checkliste", t_files: "Dateien & Anhänge (Lokal)", t_files_hint: "Browser können Dateien nicht automatisch verschieben. Speichere deine Dateien in diesem Ordner und wähle sie hier aus, um den Pfad zu verknüpfen.", t_hist: "Historie", add_point: "Punkt hinzufügen", attach_file: "Dateinamen verknüpfen", save_path: "Pfad speichern",
        s_new: "Neues Projekt-Stack", s_edit: "Projekt-Stack bearbeiten", s_name: "Projekt-Name", s_milestones: "Milestones (Stack-Checkliste)", s_tasks: "Zugehörige Aufgaben", s_add_existing_task: "Bestehende Aufgabe hinzufügen", s_add_existing_task_title: "Bestehende Aufgabe hinzufügen", s_add_existing_task_desc: "Wähle eine bestehende, aktive Aufgabe aus, um sie diesem Projekt-Stack zuzuordnen.", s_no_active_tasks: "Keine passenden aktiven Aufgaben gefunden.", s_task_added_to_stack: "„{n}“ wurde dem Stack hinzugefügt.", s_remove_from_stack: "Aus Stack entfernen", s_task_removed_from_stack: "„{n}“ wurde aus dem Stack entfernt.",
        set_title: "Einstellungen", set_gen: "Allgemein & Layout", set_team: "Team & Profil", set_data: "Stammdaten", set_lang: "Sprache / Language", set_color: "Custom Hauptfarbe", default: "Standard", set_logo: "Firmenlogo (PDF Export)", logo_desc: "Lade ein JPG oder PNG hoch. Es wird oben links (ca. 3 cm breit) im PDF platziert.", set_folder: "Stamm-Ordner für Dateien", folder_desc: "Lege hier deinen lokalen Ordner fest, in den du deine Projekt-Dateien speicherst (z.B. C:\\Projekte\\Dateien\\). ProMan speichert dann nur noch die Pfade dorthin, um Backups klein zu halten.", set_views: "Ansichten (Sidebar)", views_desc: "Ordne die Reihenfolge der Links links in der Sidebar und blende sie ein/aus.", set_sc: "Tastenkürzel", search_sc: "Suche (Strg + Taste)", set_notif: "Benachrichtigungen", notif_desc: "Steuert die Meldungen oben rechts in der Glocke.", overdue: "Überfällig anzeigen", due_today: "Heute fällig anzeigen", rem_1: "Erinnerung 1:", rem_2: "Erinnerung 2 (Optional):", set_autodel: "Auto-Löschen (Abgeschlossen)", set_trash: "Papierkorb Auto-Leeren", never: "Nie löschen", manual: "Manuell leeren", days: "Tage", weeks: "Wochen", months: "Monate", years: "Jahre", hours: "Stunden", mins: "Minuten", my_profile: "Mein Profil", my_profile_desc: "Wähle den Nutzer aus, der dieses Gerät gerade bedient.", team_mgmt: "Team Mitglieder verwalten", team_mgmt_desc: "Füge Kollegen hinzu, um ihnen Aufgaben zuzuordnen.", name: "Name", avatar_url: "Avatar URL (Optional)", set_status: "Kanban Status (Spalten)", set_sh: "Stakeholder (Kunden/Abteilungen)", pick_color: "Farbe wählen:", create: "Anlegen", set_buckets: "Buckets (Kategorien)", add: "Hinzufügen", set_defcl: "Standard Checkliste", defcl_desc: "Wird bei neuen Aufgaben automatisch geladen.", close_apply: "Schliessen & Übernehmen",
        toast_saved: "Erfolgreich gespeichert.", toast_deleted: "Gelöscht.", toast_pdf: "PDF exportiert.", toast_error: "Ein Fehler ist aufgetreten.",
        list_task_stack: "Aufgabe / Stack", list_time: "Aufwand (Ist / Soll)", list_prog: "Fortschritt", list_files: "Dateien",
        settings: "Einstellungen", no_project: "Einzelaufgabe (Kein Projekt)", compact_toggle: "Kompakt-Ansicht Umschalten", theme_toggle: "Light/Dark Mode", filter_menu_title: "Filtermenü", notif_title: "Benachrichtigungen", user_title: "Aktueller Benutzer (Profil-Einstellungen)", export_title: "Export & Backup", daily: "Täglich", weekly: "Wöchentlich", monthly: "Monatlich", yearly: "Jährlich", custom: "Benutzerdefiniert...", choose_files: "Dateien auswählen", no_file_chosen: "Keine Datei ausgewählt", file_chosen: "Datei(en) ausgewählt", quick_add: "Schnelleingabe (Enter)", col_adjust: "Spalten anpassen", master_data: "STAMMDATEN", planning: "PLANUNG", details: "DETAILS", user: "Benutzer", user_select: "Benutzer", start_date: "Startdatum", due_date: "Fälligkeit", recurrence: "Wiederholung", notes: "Notizen", checklist: "Checklistenpunkte", files: "Dateien / Pfade", history: "Historie", standalone_tasks: "Einzelaufgaben", time_effort: "Zeiten (Aufwand)", activity_chart_title: "Aktivitätsverlauf (Zeiterfassung)", actual: "Ist", target: "Soll", tasks: "Aufgaben", milestones: "Milestones", day: "Tag", week: "Woche", month: "Monat", year: "Jahr", today: "Heute", new_marker: "Neuer Marker", marker_hint: "Zieh den Button auf die Leiste oder klicke ihn, um ein Datum in der Zukunft festzulegen.", no_cl_points: "Keine Checklistenpunkte vorhanden.", due: "Fällig", priority: "Priorität", open_details: "Details öffnen", select_task: "Aufgabe wählen", timer_hint: "Klicke auf Stopp, um den Timer zu beenden. Die Zeit wird automatisch auf 0.25h gerundet und verbucht.", time_manual: "Zeit manuell eintragen", task: "Aufgabe", date: "Datum", note_opt: "Notiz (optional)", what_done: "Was hast du gemacht?", log_time: "Zeit eintragen", booking_history: "Buchungs-Historie", duration: "Dauer", image: "Bild", action: "Aktion", title: "Titel", color: "Farbe", none: "Keine",
        no_stakeholder: "Kein Stakeholder", no_bucket: "Kein Bucket", nobody: "-- Niemand --", col_completed: "Abgeschlossen", status_paused: "Pausiert", btn_pause: "Pausieren", btn_resume: "Fortsetzen", btn_complete: "Abschliessen", btn_reopen: "Wiedereröffnen",
        set_presets: "Voreinstellungen", preset_task_title: "Vorlagen für Aufgaben", preset_stack_title: "Vorlagen für Stacks", preset_new: "Neue Vorlage", preset_none: "Noch keine Vorlage. Lege eine an, um Felder automatisch vorzubelegen.", preset_default: "Standard", preset_make_default: "Als Standard festlegen", preset_keep: "— nicht vorbelegen —", preset_name_ph: "Name der Vorlage", preset_untitled: "Neue Vorlage", preset_apply: "Voreinstellung anwenden", preset_pick: "— Vorlage wählen —", preset_applied: "Vorlage „{n}“ angewandt", preset_cl_ph: "Ein Checkpunkt pro Zeile", preset_note_ph: "Voreingetragene Notiz …", notes: "Notiz", set_workflows: "<i class='fas fa-magic'></i> Workflows", wf_title: "Automatisierungen", wf_desc: "Erstelle Wenn-Dann-Regeln, um Aufgaben automatisch zuzuweisen oder zu verschieben.", wf_new: "Neuer Workflow", wf_name: "Workflow Name", wf_trig_1: "1. WENN (Auslöser)", wf_trig_select: "-- Auslöser wählen --", wf_cond_2: "2. UND / ODER (Bedingungen - Optional)", wf_cond_add: "Bedingung hinzufügen", wf_act_3: "3. DANN (Aktion)", wf_act_add: "Aktion hinzufügen", wf_save: "Workflow Speichern", wf_cancel: "Abbrechen", wf_logic_and: "Alle müssen zutreffen (UND)", wf_logic_or: "Mindestens eine (ODER)", wf_t_t_created: "Aufgabe wird erstellt", wf_t_t_updated: "Aufgabe aktualisiert (bereits erstellt)", wf_t_t_status: "Aufgabe wechselt Status auf...", wf_t_t_paused: "Aufgabe wird pausiert", wf_t_t_resumed: "Aufgabe wird fortgesetzt", wf_t_t_comp: "Aufgabe wird abgeschlossen", wf_t_s_created: "Stack wird erstellt", wf_t_s_updated: "Stack aktualisiert (bereits erstellt)", wf_t_s_paused: "Stack wird pausiert", wf_t_s_resumed: "Stack wird fortgesetzt", wf_t_s_comp: "Stack wird abgeschlossen", wf_f_name: "Aufgabenname", wf_f_start: "Startdatum", wf_f_due: "Fälligkeitsdatum", wf_f_est: "Geschätzter Aufwand (Std)", wf_f_spent: "Bisheriger Aufwand (Std)", wf_f_rec: "Wiederholung", wf_f_notes: "Notizen (Rich Text)", wf_f_cl: "Checkliste", wf_f_hist: "Historie", wf_f_prio: "Priorität", wf_f_bucket: "Bucket", wf_f_sh: "Stakeholder", wf_f_assignee: "Zuständig", wf_f_stack: "Projekt-Stack", wf_f_duration: "Dauer (Start bis Fälligkeit in Tagen)", wf_f_effort_rem: "Restaufwand (Soll minus Ist in Std)", wf_op_eq: "Ist gleich", wf_op_neq: "Ist NICHT", wf_op_cont: "Enthält", wf_op_ncont: "Enthält NICHT", wf_op_gt: "Ist grösser als", wf_op_lt: "Ist kleiner als", wf_op_d_eq: "Ist genau am (Datum)", wf_op_d_past: "Ist vergangen", wf_op_d_less: "Ist in weniger als X Tagen", wf_op_d_more: "Ist in mehr als X Tagen", wf_days: "Tage",
        wf_act_set_stat: "Setze Status auf...", wf_act_set_prio: "Setze Priorität auf...", wf_act_set_ass: "Weise Benutzer zu...", wf_act_set_buck: "Verschiebe in Bucket...", wf_act_set_sh: "Weise Stakeholder zu...", wf_act_add_note: "Notiz hinzufügen...", wf_act_notif_bell: "Erzeuge Benachrichtigung (Glocke)...", wf_act_notif_toast: "Erzeuge Benachrichtigung (Toast)...", wf_act_notif_modal: "Erzeuge Benachrichtigung (Modal)...", wf_act_notif_push: "Erzeuge Benachrichtigung (Push)...", wf_act_set_due_rel: "Verschiebe Fälligkeit um X Tage", wf_act_set_start_tdy: "Setze Startdatum auf Heute", wf_act_clear_due: "Entferne Fälligkeitsdatum", wf_act_add_est: "Erhöhe geschätzte Zeit um X Std", wf_act_set_est: "Setze geschätzte Zeit auf X Std", wf_hours: "Stunden", wf_days_from_now: "Tage ab heute", wf_no_val_needed: "(Kein Wert benötigt)",
        wf_act_send_email: "Sende E-Mail mit Infos..."
    },
    en: {
        today_morning: "Good morning", today_day: "Hello", today_evening: "Good evening",
        today_of: "of", today_booked: "booked", today_missing_pre: "Still", today_missing_post: "hours open. {n} tasks are due or overdue.",
        today_complete: "The day is fully booked. {n} tasks are still open.",
        today_book_time: "Book time", mark_done: "Complete", wf_any_status: "— Any status —", preset_cl_add: "Add item", preset_cl_item_ph: "Checklist item", preset_cl_time_title: "Time in hours (optional)", today_running: "Running timers", today_urgent: "Due and overdue",
        today_all_tasks: "All tasks", today_none_urgent: "Nothing overdue", today_none_urgent_sub: "All scheduled tasks lie in the future.",
        today_this_week: "This week", today_next_week: "Next week", today_later: "Later", milestones_empty: "No stacks with milestones found.", checklists_empty: "No tasks with checklist items found.", act_task_created: "Task \"{n}\" created", act_task_edited: "Task \"{n}\" edited", act_task_done: "Task \"{n}\" completed", act_task_reopened: "Task \"{n}\" reopened", act_task_paused: "Task \"{n}\" paused", act_task_resumed: "Task \"{n}\" resumed", act_stack_created: "Stack \"{n}\" created", act_cp: "Checkpoint", act_ms: "Milestone", act_cp_done: "{k} \"{n}\" checked", act_cp_reopened: "{k} \"{n}\" reopened", act_cp_edited: "{k} \"{n}\" edited", act_cp_added: "{k} added to \"{n}\"", act_cp_deleted: "{k} \"{n}\" deleted", act_stack_paused: "Stack \"{n}\" paused", act_stack_resumed: "Stack \"{n}\" resumed", act_stack_done: "Stack \"{n}\" completed",  act_stack_edited: "Stack \"{n}\" edited", act_time_booked: "{h} h booked on \"{n}\"", today_activity: "Recent activity", today_no_activity: "No activity yet", rel_now: "just now",  today_unbooked: "Not booked", today_all_booked: "All booked", today_week_quota: "Weekly quota", today_trend: "Hours per bucket", today_no_bookings: "No bookings", today_week_total: "Week total", today_last7: "last 7 days", today_status_dist: "Status split", today_open_checklist_extra: "+ {n} open checklist items/milestones", today_open_stacks_extra: "+ {n} open stacks", status_todo: "Open", status_inprogress: "In progress", status_review: "Review", today_prio_dist: "Open priorities", today_done_share: "Done overall", today_done_week: "done this week", today_open: "open", today_overdue: "overdue",
        tt_title: "Time account & open days", tt_prev: "Previous month", tt_next: "Next month", tt_add_absence: "Log absence", tt_add_time: "Log time", tt_detail_title: "Booked on selected days", tt_detail_empty: "Nothing booked on the selected days yet.", tt_deleted_task: "Deleted task",
        tt_soll_todate: "Target (to date)", tt_month_total: "Month total", tt_booked_h: "Logged", tt_from_tasks: "from task bookings", tt_absence_h: "Absence", tt_absence_sub: "Vacation / Sick / Holiday", tt_saldo: "Balance", tt_saldo_sub: "Actual + absence − target", tt_open_days: "Open days", tt_open_days_sub: "incompletely logged",
        tt_open_outside: "open days outside this month", tt_oldest: "oldest", tt_jump_there: "Jump there",
        tt_leg_ok: "Complete", tt_leg_partial: "Partial", tt_leg_missing: "Not logged", tt_leg_abs: "Absence", tt_leg_free: "Non-working", tt_select_hint: "Click a day to select · Shift+click for a range",
        tt_selected: "day(s) selected", tt_half_day: "Half days", tt_remove_abs: "Remove absence", tt_abs_removed: "absence(s) removed.", tt_nothing_removed: "No absence found to remove.",
        tt_open_list: "Open days – quick booking", tt_select_all_open: "Select all open", tt_all_complete: "All working days this month are fully logged.", tt_missing: "Missing", tt_of: "of", tt_book_task: "Log time",
        tt_abs_in_month: "Absences this month", tt_booked: "logged", tt_days_booked: "day(s) logged", tt_skipped_free: "non-working days skipped", tt_no_open: "No open days.", tt_nonworkday: "non-working",
        tt_need_dates: "Please choose a start and end date.", tt_range_invalid: "End date is before start date.", tt_abs_modal_title: "Log absence", tt_abs_type: "Type of absence", tt_from: "From", tt_to: "To", tt_abs_modal_hint: "Non-working days (e.g. weekends) are skipped automatically.",
        abs_vacation: "Vacation", abs_sick: "Sick", abs_holiday: "Public holiday", abs_other: "Compensation",
        set_timeacct: "Time account (target hours)", set_timeacct_desc: "Defines how many hours must be logged per working day. Time tracking uses this to detect incompletely logged days.", set_target_h: "Target hours / working day", set_track_from: "Check from",
        view_today: "Hub", view_kanban: "Kanban Board", view_list: "List", view_notes: "Notes", view_planner: "Planning", view_schedule: "Schedule", view_stakeholder: "Stakeholders", view_buckets: "Buckets", view_timeline: "Gantt Chart", view_stacks: "Project Stacks", view_checklists: "Checklists", view_time: "Time Tracking", sched_history: "History", view_dependencies: "Dependencies", dep_start: "Start", dep_no_stack: "No stack", dep_depends_on: "Depends on", dep_unlink_hint: "Click to remove connections", dep_unlink_confirm: "Remove all predecessor links of this item?", dep_unlinked: "Connections removed", sort_manual: "Manual", sort_name: "Name", sort_due: "Due", sort_priority: "Priority", dep_connect_mode: "Connect", dep_connect_on: "Connect mode: tap source, then target", dep_tap_target: "Now tap the target element", dep_drag_hint2: "Drag or tap „Connect“", dep_precond: "Preconditions (checkpoints)", dep_link_invalid: "This link is not possible (only task→task or checkpoint→stack).", dep_drag_hint: "Drag a node to link", dep_only_tasks: "Links are only possible between tasks.", dep_exists: "This link already exists.", dep_cycle: "That would create a cycle and is not allowed.", dep_linked: "\"{a}\" is now a predecessor of \"{b}\".", dep_end: "End (locked)", dep_ready: "Ready", dep_blocked: "Blocked", dep_no_tasks: "No tasks", dep_empty_title: "No dependencies", dep_empty_sub: "Set predecessors on a task to see the chains here.",
        search: "Search...", new: "New", new_task: "New Task", new_stack: "New Stack",
        filter_hide_comp: "Hide Completed", filter_hide_paused: "Hide Paused", filter_by: "Filter by:", btn_users: "Users", btn_stacks: "Stacks", btn_sh: "Stakeholders", btn_buckets: "Buckets", btn_status: "Status",
        export_share: "Share Filtered View (JSON)", export_excel_view: "Excel (View)", export_excel_time: "Excel (Time)", export_pdf: "PDF (Filtered)", export_word: "Word Document (.doc)", export_ics: "Export Calendar (.ics)", export_backup: "Download Backup", import_backup: "Import Backup / Shared File",
        modal_rate: "Submit Rating", modal_rate_desc: "You have completed this project/task. How did it go?", rate_comm: "Communication & Transparency", rate_time: "Schedule Adherence", rate_qual: "Quality of Results", rate_team: "Teamwork & Dynamics", rate_crea: "Creativity & Innovation", rate_satis: "Customer Satisfaction", rate_skip: "Skip", save: "Save", cancel: "Cancel", delete: "Delete", share: "Share",
        merge_title: "Merge Tasks into Stack", merge_desc: "Select an existing project stack or create a new one.", merge_existing: "Existing Stack:", merge_or: "OR", merge_new: "Create New Stack (Name):", merge_btn: "Merge",
        marker_title_edit: "Edit Marker", marker_title_new: "New Marker", marker_name: "Marker Name", marker_date: "Date",
        time_title: "Edit Time Log", time_task: "Task", time_date: "Date", time_hours: "Hours", time_note: "Note",
        task_new: "Create Task", task_edit: "Edit Task", tab_gen: "General", tab_plan: "Planning & Time", tab_detail: "Checklist & Files", tab_rating: "Rating",
        t_name: "Task Name", t_stack: "Associated Project Stack", t_assignee: "Assignee (User)", t_status: "Status", t_prio: "Priority", prio_low: "Low", prio_med: "Medium", prio_high: "High", t_sh: "Stakeholder", t_bucket: "Bucket (Category)", t_start: "Start Date", t_due: "Due Date", t_est: "Estimated Effort (Hrs)", t_spent: "Spent Effort (Hrs)", t_rec: "Recurrence", t_rtf: "Notes (Rich Text)", t_cl: "Checklist", t_files: "Files & Attachments (Local)", t_files_hint: "Browsers cannot automatically move files. Save your files in this folder and select them here to link the path.", t_hist: "History", add_point: "Add Point", attach_file: "Link Filenames", save_path: "Save Path",
        s_new: "New Project Stack", s_edit: "Edit Project Stack", s_name: "Project Name", s_milestones: "Milestones (Stack Checklist)", s_tasks: "Associated Tasks", s_add_existing_task: "Add Existing Task", s_add_existing_task_title: "Add Existing Task", s_add_existing_task_desc: "Choose an existing, active task to assign to this project stack.", s_no_active_tasks: "No matching active tasks found.", s_task_added_to_stack: "\"{n}\" was added to the stack.", s_remove_from_stack: "Remove from stack", s_task_removed_from_stack: "\"{n}\" was removed from the stack.",
        set_title: "Settings", set_gen: "General & Layout", set_team: "Team & Profile", set_data: "Master Data", set_lang: "Language", set_color: "Custom Main Color", default: "Default", set_logo: "Company Logo (PDF Export)", logo_desc: "Upload a JPG or PNG. It will be placed in the top left (approx. 3 cm wide) of the PDF.", set_folder: "Root Folder for Files", folder_desc: "Define your local folder where you save your project files (e.g. C:\\Projects\\Files\\). ProMan will then only store the paths there to keep backups small.", set_views: "Views (Sidebar)", views_desc: "Arrange the order of the links on the left in the sidebar and show/hide them.", set_sc: "Keyboard Shortcuts", search_sc: "Search (Ctrl + Key)", set_notif: "Notifications", notif_desc: "Controls the messages in the top right bell.", overdue: "Show Overdue", due_today: "Show Due Today", rem_1: "Reminder 1:", rem_2: "Reminder 2 (Optional):", set_autodel: "Auto-Delete (Completed)", set_trash: "Trash Auto-Empty", never: "Never delete", manual: "Empty manually", days: "Days", weeks: "Weeks", months: "Months", years: "Years", hours: "Hours", mins: "Minutes", my_profile: "My Profile", my_profile_desc: "Select the user currently operating this device.", team_mgmt: "Manage Team Members", team_mgmt_desc: "Add colleagues to assign tasks to them.", name: "Name", avatar_url: "Avatar URL (Optional)", set_status: "Kanban Status (Columns)", set_sh: "Stakeholders (Clients/Depts)", pick_color: "Pick Color:", create: "Create", set_buckets: "Buckets (Categories)", add: "Add", set_defcl: "Default Checklist", defcl_desc: "Automatically loaded for new tasks.", close_apply: "Close & Apply",
        toast_saved: "Saved successfully.", toast_deleted: "Deleted.", toast_pdf: "PDF exported.", toast_error: "An error occurred.",
        list_task_stack: "Task / Stack", list_time: "Effort (Actual / Target)", list_prog: "Progress", list_files: "Files",
        settings: "Settings", no_project: "Single Task (No Project)", compact_toggle: "Toggle Compact View", theme_toggle: "Light/Dark Mode", filter_menu_title: "Filter Menu", notif_title: "Notifications", user_title: "Current User (Profile Settings)", export_title: "Export & Backup", daily: "Daily", weekly: "Weekly", monthly: "Monthly", yearly: "Yearly", custom: "Custom...", choose_files: "Choose Files", no_file_chosen: "No file chosen", file_chosen: "File(s) chosen", quick_add: "Quick Add (Enter)", col_adjust: "Adjust Columns", master_data: "MASTER DATA", planning: "PLANNING", details: "DETAILS", user: "User", user_select: "User", start_date: "Start Date", due_date: "Due Date", recurrence: "Recurrence", notes: "Notes", checklist: "Checklist Points", files: "Files / Paths", history: "History", standalone_tasks: "Standalone Tasks", time_effort: "Time (Effort)", activity_chart_title: "Activity History (Time Tracking)", actual: "Actual", target: "Target", tasks: "Tasks", milestones: "Milestones", day: "Day", week: "Week", month: "Month", year: "Year", today: "Today", new_marker: "New Marker", marker_hint: "Drag the button to the bar or click it to set a future date.", no_cl_points: "No checklist points available.", due: "Due", priority: "Priority", open_details: "Open Details", select_task: "Select Task", timer_hint: "Click stop to end the timer. Time is automatically rounded to 0.25h and logged.", time_manual: "Log Time Manually", task: "Task", date: "Date", note_opt: "Note (optional)", what_done: "What did you do?", log_time: "Log Time", booking_history: "Booking History", duration: "Duration", image: "Image", action: "Action", title: "Title", color: "Color", none: "None",
        no_stakeholder: "No Stakeholder", no_bucket: "No Bucket", nobody: "-- Nobody --", col_completed: "Completed", status_paused: "Paused", btn_pause: "Pause", btn_resume: "Resume", btn_complete: "Complete", btn_reopen: "Reopen",
        set_presets: "Presets", preset_task_title: "Task templates", preset_stack_title: "Stack templates", preset_new: "New preset", preset_none: "No preset yet. Create one to pre-fill fields automatically.", preset_default: "Default", preset_make_default: "Set as default", preset_keep: "— don't pre-fill —", preset_name_ph: "Preset name", preset_untitled: "New preset", preset_apply: "Apply preset", preset_pick: "— pick a preset —", preset_applied: "Preset “{n}” applied", preset_cl_ph: "One checkpoint per line", preset_note_ph: "Pre-filled note …", notes: "Note", set_workflows: "<i class='fas fa-magic'></i> Automations", wf_title: "Automations", wf_desc: "Create If-Then rules to automatically assign or move tasks.", wf_new: "New Workflow", wf_name: "Workflow Name", wf_trig_1: "1. IF (Trigger)", wf_trig_select: "-- Select Trigger --", wf_cond_2: "2. AND / OR (Conditions - Optional)", wf_cond_add: "Add Condition", wf_act_3: "3. THEN (Action)", wf_act_add: "Add Action", wf_save: "Save Workflow", wf_cancel: "Cancel", wf_logic_and: "All must match (AND)", wf_logic_or: "At least one (OR)",
        wf_t_t_created: "Task is created", wf_t_t_updated: "Task is updated (already created)", wf_t_t_status: "Task changes status to...", wf_t_t_paused: "Task is paused", wf_t_t_resumed: "Task is resumed", wf_t_t_comp: "Task is completed", wf_t_s_created: "Stack is created", wf_t_s_updated: "Stack is updated (already created)", wf_t_s_paused: "Stack is paused", wf_t_s_resumed: "Stack is resumed", wf_t_s_comp: "Stack is completed",
        wf_f_name: "Task Name", wf_f_start: "Start Date", wf_f_due: "Due Date", wf_f_est: "Estimated Effort (Hrs)", wf_f_spent: "Spent Effort (Hrs)", wf_f_rec: "Recurrence", wf_f_notes: "Notes (Rich Text)", wf_f_cl: "Checklist", wf_f_hist: "History", wf_f_prio: "Priority", wf_f_bucket: "Bucket", wf_f_sh: "Stakeholder", wf_f_assignee: "Assignee", wf_f_stack: "Project Stack", wf_f_duration: "Duration (Start to Due in Days)", wf_f_effort_rem: "Effort Remaining (Target minus Actual in Hrs)",
        wf_op_eq: "Equals", wf_op_neq: "Does NOT equal", wf_op_cont: "Contains", wf_op_ncont: "Does NOT contain", wf_op_gt: "Is greater than", wf_op_lt: "Is less than", wf_op_d_eq: "Is exactly on (Date)", wf_op_d_past: "Is in the past", wf_op_d_less: "Is in less than X days", wf_op_d_more: "Is in more than X days", wf_days: "Days",
        wf_act_set_stat: "Set Status to...", wf_act_set_prio: "Set Priority to...", wf_act_set_ass: "Assign User...", wf_act_set_buck: "Move to Bucket...", wf_act_set_sh: "Assign Stakeholder...", wf_act_add_note: "Add Note...", wf_act_notif_bell: "Create Notification (Bell)...", wf_act_notif_toast: "Create Notification (Toast)...", wf_act_notif_modal: "Create Notification (Modal)...", wf_act_notif_push: "Create Notification (Push)...", wf_act_set_due_rel: "Shift Due Date by X Days", wf_act_set_start_tdy: "Set Start Date to Today", wf_act_clear_due: "Remove Due Date", wf_act_add_est: "Increase Estimated Time by X Hrs", wf_act_set_est: "Set Estimated Time to X Hrs", wf_hours: "Hours", wf_days_from_now: "Days from today", wf_no_val_needed: "(No value needed)", wf_act_send_email: "Send Email with info..."
    },
    fr: {
        today_morning: "Bonjour", today_day: "Salut", today_evening: "Bonsoir",
        today_of: "sur", today_booked: "saisi", today_missing_pre: "Encore", today_missing_post: "heures ouvertes. {n} tâches sont dues ou en retard.",
        today_complete: "La journée est complète. {n} tâches restent ouvertes.",
        today_book_time: "Saisir du temps", mark_done: "Terminer", wf_any_status: "— Tout statut —", preset_cl_add: "Ajouter un point", preset_cl_item_ph: "Point de checklist", preset_cl_time_title: "Temps en heures (optionnel)", today_running: "Minuteurs actifs", today_urgent: "Dû et en retard",
        today_all_tasks: "Toutes les tâches", today_none_urgent: "Rien en retard", today_none_urgent_sub: "Toutes les tâches planifiées sont à venir.",
        today_this_week: "Cette semaine", today_next_week: "Semaine prochaine", today_later: "Plus tard", milestones_empty: "Aucun stack avec jalons.", checklists_empty: "Aucune tâche avec points de contrôle.", act_task_created: "Tâche « {n} » créée", act_task_edited: "Tâche « {n} » modifiée", act_task_done: "Tâche « {n} » terminée", act_task_reopened: "Tâche « {n} » rouverte", act_task_paused: "Tâche « {n} » suspendue", act_task_resumed: "Tâche « {n} » reprise", act_stack_created: "Stack « {n} » créé", act_cp: "Point", act_ms: "Jalon", act_cp_done: "{k} « {n} » coché", act_cp_reopened: "{k} « {n} » rouvert", act_cp_edited: "{k} « {n} » modifié", act_cp_added: "{k} ajouté à « {n} »", act_cp_deleted: "{k} « {n} » supprimé", act_stack_paused: "Stack « {n} » suspendu", act_stack_resumed: "Stack « {n} » repris", act_stack_done: "Stack « {n} » terminé",  act_stack_edited: "Stack « {n} » modifié", act_time_booked: "{h} h saisies sur « {n} »", today_activity: "Activité récente", today_no_activity: "Aucune activité", rel_now: "à l'instant",  today_unbooked: "Non saisi", today_all_booked: "Tout saisi", today_week_quota: "Quota hebdo", today_trend: "Heures par catégorie", today_no_bookings: "Aucune saisie", today_week_total: "Total semaine", today_last7: "7 derniers jours", today_status_dist: "Répartition statut", today_open_checklist_extra: "+ {n} points de contrôle/jalons ouverts", today_open_stacks_extra: "+ {n} stacks ouverts", status_todo: "Ouvert", status_inprogress: "En cours", status_review: "Révision", today_prio_dist: "Priorités ouvertes", today_done_share: "Terminé au total", today_done_week: "fait cette semaine", today_open: "ouvert", today_overdue: "en retard",
        tt_title: "Compte de temps & jours ouverts", tt_prev: "Mois précédent", tt_next: "Mois suivant", tt_add_absence: "Saisir une absence", tt_add_time: "Saisir du temps", tt_detail_title: "Saisi les jours choisis", tt_detail_empty: "Rien saisi les jours choisis.", tt_deleted_task: "Tâche supprimée",
        tt_soll_todate: "Objectif (à ce jour)", tt_month_total: "Total du mois", tt_booked_h: "Saisi", tt_from_tasks: "des saisies sur tâches", tt_absence_h: "Absence", tt_absence_sub: "Congés / Maladie / Férié", tt_saldo: "Solde", tt_saldo_sub: "Réel + absence − objectif", tt_open_days: "Jours ouverts", tt_open_days_sub: "saisie incomplète",
        tt_open_outside: "jours ouverts hors de ce mois", tt_oldest: "le plus ancien", tt_jump_there: "Y aller",
        tt_leg_ok: "Complet", tt_leg_partial: "Partiel", tt_leg_missing: "Non saisi", tt_leg_abs: "Absence", tt_leg_free: "Non travaillé", tt_select_hint: "Cliquez sur un jour pour le sélectionner · Maj+clic pour une période",
        tt_selected: "jour(s) sélectionné(s)", tt_half_day: "Demi-journées", tt_remove_abs: "Supprimer l'absence", tt_abs_removed: "absence(s) supprimée(s).", tt_nothing_removed: "Aucune absence à supprimer.",
        tt_open_list: "Jours ouverts – saisie rapide", tt_select_all_open: "Tout sélectionner", tt_all_complete: "Tous les jours ouvrés de ce mois sont complets.", tt_missing: "Manquant", tt_of: "sur", tt_book_task: "Saisir du temps",
        tt_abs_in_month: "Absences ce mois-ci", tt_booked: "saisi", tt_days_booked: "jour(s) saisi(s)", tt_skipped_free: "jours non travaillés ignorés", tt_no_open: "Aucun jour ouvert.", tt_nonworkday: "non travaillé",
        tt_need_dates: "Veuillez choisir une date de début et de fin.", tt_range_invalid: "La date de fin précède la date de début.", tt_abs_modal_title: "Saisir une absence", tt_abs_type: "Type d'absence", tt_from: "Du", tt_to: "Au", tt_abs_modal_hint: "Les jours non travaillés (week-ends) sont ignorés automatiquement.",
        abs_vacation: "Congés", abs_sick: "Maladie", abs_holiday: "Jour férié", abs_other: "Compensation",
        view_today: "Hub", view_kanban: "Tableau Kanban", view_list: "Liste", view_notes: "Notes", view_planner: "Planification", view_schedule: "Calendrier", view_stakeholder: "Parties prenantes", view_buckets: "Catégories (Buckets)", view_timeline: "Diagramme de Gantt", view_stacks: "Piles de projets", view_checklists: "Listes de contrôle", view_time: "Suivi du temps", sched_history: "Historique", view_dependencies: "Dépendances", dep_start: "Départ", dep_no_stack: "Sans stack", dep_depends_on: "Dépend de", dep_unlink_hint: "Cliquer pour retirer les liens", dep_unlink_confirm: "Retirer tous les prédécesseurs de cet élément ?", dep_unlinked: "Liens retirés", sort_manual: "Manuel", sort_name: "Nom", sort_due: "Échéance", sort_priority: "Priorité", dep_connect_mode: "Relier", dep_connect_on: "Mode relier : touchez la source puis la cible", dep_tap_target: "Touchez maintenant la cible", dep_drag_hint2: "Glisser ou toucher « Relier »", dep_precond: "Préconditions (points)", dep_link_invalid: "Ce lien est impossible (seulement tâche→tâche ou point→stack).", dep_drag_hint: "Glisser un nœud pour relier", dep_only_tasks: "Les liens ne sont possibles qu'entre tâches.", dep_exists: "Ce lien existe déjà.", dep_cycle: "Cela créerait un cycle, interdit.", dep_linked: "\"{a}\" est désormais prédécesseur de \"{b}\".", dep_end: "Fin (verrouillé)", dep_ready: "Prêt", dep_blocked: "Bloqué", dep_no_tasks: "Aucune tâche", dep_empty_title: "Aucune dépendance", dep_empty_sub: "Définissez des prédécesseurs sur une tâche pour voir les chaînes ici.",
        search: "Rechercher...", new: "Nouveau", new_task: "Nouvelle tâche", new_stack: "Nouvelle pile",
        filter_hide_comp: "Masquer les terminés", filter_hide_paused: "Masquer les suspendus", filter_by: "Filtrer par :", btn_users: "Utilisateurs", btn_stacks: "Piles", btn_sh: "Parties prenantes", btn_buckets: "Catégories", btn_status: "Statut",
        export_share: "Partager la vue filtrée (JSON)", export_excel_view: "Excel (Vue)", export_excel_time: "Excel (Temps)", export_pdf: "PDF (Filtré)", export_word: "Document Word (.doc)", export_ics: "Exporter le calendrier (.ics)", export_backup: "Télécharger la sauvegarde", import_backup: "Importer une sauvegarde / un fichier partagé",
        modal_rate: "Soumettre une évaluation", modal_rate_desc: "Vous avez terminé ce projet/tâche. Comment ça s'est passé ?", rate_comm: "Communication & Transparence", rate_time: "Respect des délais", rate_qual: "Qualité des résultats", rate_team: "Travail d'équipe & Dynamique", rate_crea: "Créativité & Innovation", rate_satis: "Satisfaction du client", rate_skip: "Passer", save: "Enregistrer", cancel: "Annuler", delete: "Supprimer", share: "Partager",
        merge_title: "Fusionner les tâches dans la pile", merge_desc: "Sélectionnez une pile de projets existante ou créez-en une nouvelle.", merge_existing: "Pile existante :", merge_or: "OU", merge_new: "Créer une nouvelle pile (Nom) :", merge_btn: "Fusionner",
        marker_title_edit: "Modifier le marqueur", marker_title_new: "Nouveau marqueur", marker_name: "Nom du marqueur", marker_date: "Date",
        time_title: "Modifier l'enregistrement", time_task: "Tâche", time_date: "Date", time_hours: "Heures", time_note: "Note",
        task_new: "Créer une tâche", task_edit: "Modifier la tâche", tab_gen: "Général", tab_plan: "Planification & Temps", tab_detail: "Liste & Fichiers", tab_rating: "Évaluation",
        t_name: "Nom de la tâche", t_stack: "Pile de projets associée", t_assignee: "Responsable (Utilisateur)", t_status: "Statut", t_prio: "Priorité", prio_low: "Basse", prio_med: "Moyenne", prio_high: "Haute", t_sh: "Partie prenante", t_bucket: "Catégorie (Bucket)", t_start: "Date de début", t_due: "Date d'échéance", t_est: "Effort estimé (Heures)", t_spent: "Effort dépensé (Heures)", t_rec: "Récurrence", t_rtf: "Notes (Texte riche)", t_cl: "Liste de contrôle", t_files: "Fichiers & Pièces jointes (Local)", t_files_hint: "Les navigateurs ne peuvent pas déplacer automatiquement les fichiers. Enregistrez vos fichiers dans ce dossier et sélectionnez-les ici pour lier le chemin.", t_hist: "Historique", add_point: "Ajouter un point", attach_file: "Lier les noms de fichiers", save_path: "Enregistrer le chemin",
        s_new: "Nouvelle pile de projets", s_edit: "Modifier la pile de projets", s_name: "Nom du projet", s_milestones: "Jalons (Liste de la pile)", s_tasks: "Tâches associées", s_add_existing_task: "Ajouter une tâche existante", s_add_existing_task_title: "Ajouter une tâche existante", s_add_existing_task_desc: "Choisissez une tâche existante et active à associer à cette pile de projets.", s_no_active_tasks: "Aucune tâche active correspondante trouvée.", s_task_added_to_stack: "« {n} » a été ajoutée à la pile.", s_remove_from_stack: "Retirer de la pile", s_task_removed_from_stack: "« {n} » a été retirée de la pile.",
        set_title: "Paramètres", set_gen: "Général & Mise en page", set_team: "Équipe & Profil", set_data: "Données de base", set_lang: "Langue", set_color: "Couleur principale", default: "Par défaut", set_logo: "Logo de l'entreprise (Export PDF)", logo_desc: "Téléchargez un JPG ou PNG. Il sera placé en haut à gauche (environ 3 cm de large) du PDF.", set_folder: "Dossier racine des fichiers", folder_desc: "Définissez votre dossier local où vous enregistrez vos fichiers de projet (ex. C:\\Projets\\Fichiers\\). ProMan n'y enregistrera que les chemins d'accès pour limiter la taille des sauvegardes.", set_views: "Vues (Barre latérale)", views_desc: "Organisez l'ordre des liens à gauche dans la barre latérale et masquez/affichez-les.", set_sc: "Raccourcis clavier", search_sc: "Recherche (Ctrl + Touche)", set_notif: "Notifications", notif_desc: "Contrôle les messages dans la cloche en haut à droite.", overdue: "Afficher les retards", due_today: "Afficher à échéance aujourd'hui", rem_1: "Rappel 1 :", rem_2: "Rappel 2 (Facultatif) :", set_autodel: "Suppression auto (Terminé)", set_trash: "Vidage auto de la corbeille", never: "Ne jamais supprimer", manual: "Vider manuellement", days: "Jours", weeks: "Semaines", months: "Mois", years: "Années", hours: "Heures", mins: "Minutes", my_profile: "Mon profil", my_profile_desc: "Sélectionnez l'utilisateur qui utilise actuellement cet appareil.", team_mgmt: "Gérer les membres de l'équipe", team_mgmt_desc: "Ajoutez des collègues pour leur assigner des tâches.", name: "Nom", avatar_url: "URL de l'avatar (Facultatif)", set_status: "Statut Kanban (Colonnes)", set_sh: "Parties prenantes (Clients/Dépts)", pick_color: "Choisir la couleur :", create: "Créer", set_buckets: "Catégories (Buckets)", add: "Ajouter", set_defcl: "Liste de contrôle par défaut", defcl_desc: "Chargée automatiquement pour les nouvelles tâches.", close_apply: "Fermer & Appliquer",
        toast_saved: "Enregistré avec succès.", toast_deleted: "Supprimé.", toast_pdf: "PDF exporté.", toast_error: "Une erreur est survenue.",
        list_task_stack: "Tâche / Pile", list_time: "Effort (Actuel / Cible)", list_prog: "Progrès", list_files: "Fichiers",
        settings: "Paramètres", no_project: "Tâche unique (Pas de projet)", compact_toggle: "Basculer la vue compacte", theme_toggle: "Mode Clair/Sombre", filter_menu_title: "Menu de filtrage", notif_title: "Notifications", user_title: "Utilisateur actuel (Paramètres du profil)", export_title: "Export & Sauvegarde", daily: "Quotidien", weekly: "Hebdomadaire", monthly: "Mensuel", yearly: "Annuel", custom: "Personnalisé...", choose_files: "Choisir des fichiers", no_file_chosen: "Aucun fichier choisi", file_chosen: "Fichier(s) choisi(s)", quick_add: "Ajout rapide (Entrée)", col_adjust: "Ajuster les colonnes", master_data: "DONNÉES DE BASE", planning: "PLANIFICATION", details: "DÉTAILS", user: "Utilisateur", user_select: "Utilisateur", start_date: "Date de début", due_date: "Date d'échéance", recurrence: "Récurrence", notes: "Notes", checklist: "Points de contrôle", files: "Fichiers / Chemins", history: "Historique", standalone_tasks: "Tâches indépendantes", time_effort: "Temps (Effort)", activity_chart_title: "Historique d'activité (Suivi du temps)", actual: "Actuel", target: "Cible", tasks: "Tâches", milestones: "Jalons", day: "Jour", week: "Semaine", month: "Mois", year: "Année", today: "Aujourd'hui", new_marker: "Nouveau marqueur", marker_hint: "Faites glisser le bouton sur la barre ou cliquez dessus pour définir une date future.", no_cl_points: "Aucun point de contrôle disponible.", due: "Échéance", priority: "Priorité", open_details: "Ouvrir les détails", select_task: "Sélectionner la tâche", timer_hint: "Cliquez sur stop pour arrêter le minuteur. Le temps est automatiquement arrondi à 0,25h et enregistré.", time_manual: "Enregistrer le temps manuellement", task: "Tâche", date: "Date", note_opt: "Note (facultatif)", what_done: "Qu'avez-vous fait ?", log_time: "Enregistrer le temps", booking_history: "Historique des réservations", duration: "Durée", image: "Image", action: "Action", title: "Titre", color: "Couleur", none: "Aucun",
        no_stakeholder: "Aucune partie prenante", no_bucket: "Aucune catégorie", nobody: "-- Personne --", col_completed: "Terminé", status_paused: "En pause", btn_pause: "Suspendre", btn_resume: "Reprendre", btn_complete: "Achever", btn_reopen: "Rouvrir",
        set_presets: "Préréglages", preset_task_title: "Modèles de tâches", preset_stack_title: "Modèles de stacks", preset_new: "Nouveau modèle", preset_none: "Aucun modèle. Créez-en un pour préremplir les champs.", preset_default: "Défaut", preset_make_default: "Définir par défaut", preset_keep: "— ne pas préremplir —", preset_name_ph: "Nom du modèle", preset_untitled: "Nouveau modèle", preset_apply: "Appliquer un modèle", preset_pick: "— choisir un modèle —", preset_applied: "Modèle « {n} » appliqué", preset_cl_ph: "Un point par ligne", preset_note_ph: "Note préremplie …", notes: "Note", set_workflows: "<i class='fas fa-magic'></i> Automatisations", wf_title: "Automatisations", wf_desc: "Créez des règles Si-Alors pour assigner ou déplacer automatiquement les tâches.", wf_new: "Nouveau flux de travail", wf_name: "Nom du flux", wf_trig_1: "1. SI (Déclencheur)", wf_trig_select: "-- Sélectionner un déclencheur --", wf_cond_2: "2. ET / OU (Conditions - Facultatif)", wf_cond_add: "Ajouter une condition", wf_act_3: "3. ALORS (Action)", wf_act_add: "Ajouter une action", wf_save: "Enregistrer le flux", wf_cancel: "Annuler", wf_logic_and: "Toutes doivent correspondre (ET)", wf_logic_or: "Au moins une (OU)",
        wf_t_t_created: "La tâche est créée", wf_t_t_updated: "La tâche est mise à jour (déjà créée)", wf_t_t_status: "La tâche change de statut pour...", wf_t_t_paused: "La tâche est suspendue", wf_t_t_resumed: "La tâche est reprise", wf_t_t_comp: "La tâche est terminée", wf_t_s_created: "La pile est créée", wf_t_s_updated: "La pile est mise à jour (déjà créée)", wf_t_s_paused: "La pile est suspendue", wf_t_s_resumed: "La pile est reprise", wf_t_s_comp: "La pile est terminée",
        wf_f_name: "Nom de la tâche", wf_f_start: "Date de début", wf_f_due: "Date d'échéance", wf_f_est: "Effort estimé (Heures)", wf_f_spent: "Effort dépensé (Heures)", wf_f_rec: "Récurrence", wf_f_notes: "Notes (Texte riche)", wf_f_cl: "Liste de contrôle", wf_f_hist: "Historique", wf_f_prio: "Priorité", wf_f_bucket: "Catégorie (Bucket)", wf_f_sh: "Partie prenante", wf_f_assignee: "Responsable", wf_f_stack: "Pile de projets", wf_f_duration: "Durée (Début à Échéance en Jours)", wf_f_effort_rem: "Effort restant (Cible moins Actuel en H)",
        wf_op_eq: "Est égal à", wf_op_neq: "N'est PAS égal à", wf_op_cont: "Contient", wf_op_ncont: "Ne contient PAS", wf_op_gt: "Est supérieur à", wf_op_lt: "Est inférieur à", wf_op_d_eq: "Est exactement le (Date)", wf_op_d_past: "Est dans le passé", wf_op_d_less: "Est dans moins de X jours", wf_op_d_more: "Est dans plus de X jours", wf_days: "Jours",
        wf_act_set_stat: "Définir le statut sur...", wf_act_set_prio: "Définir la priorité sur...", wf_act_set_ass: "Assigner à l'utilisateur...", wf_act_set_buck: "Déplacer vers la catégorie...", wf_act_set_sh: "Assigner à la partie prenante...", wf_act_add_note: "Ajouter une note...", wf_act_notif_bell: "Créer une notification (Cloche)...", wf_act_notif_toast: "Créer une notification (Toast)...", wf_act_notif_modal: "Créer une notification (Modale)...", wf_act_notif_push: "Créer une notification (Push)...", wf_act_set_due_rel: "Décaler l'échéance de X jours", wf_act_set_start_tdy: "Définir la date de début à aujourd'hui", wf_act_clear_due: "Supprimer la date d'échéance", wf_act_add_est: "Augmenter le temps estimé de X Heures", wf_act_set_est: "Définir le temps estimé à X Heures", wf_hours: "Heures", wf_days_from_now: "Jours à partir d'aujourd'hui", wf_no_val_needed: "(Aucune valeur requise)", wf_act_send_email: "Envoyer un e-mail avec les infos..."
    }
};

function t(key) {
    const lang = (appData && appData.settings && appData.settings.language) ? appData.settings.language : 'de';
    return i18n[lang][key] || i18n['de'][key] || key;
}

function applyTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (el.tagName === 'INPUT' && (el.type === 'text' || el.type === 'number')) {
            el.placeholder = t(key);
        } else if (el.tagName === 'OPTION') {
            el.innerText = t(key);
        } else {
            el.innerHTML = t(key);
        }
    });
    document.querySelectorAll('[data-i18n-title]').forEach(el => {
        el.title = t(el.getAttribute('data-i18n-title'));
    });
    // This function exists in app.js, so it will be called correctly from the global scope
    if (typeof updateShortcutUI === 'function') {
        updateShortcutUI();
    }
}